name: Python CI

on:
    push:
        branches:
            - main
    pull Requests:
        branches:
            - main

jobs:
    test:
       runs-on: ubuntu-latest
       steps:
        - name: check out the code 
          uses: actions/checkout@v2
        - name: Set up python environment
          uses: actions/setup-python@v2
          with:
            python-version: '3.3'  
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: Run Tests
          run: pytest
